// <auto-generated />
namespace ServiceImplementsDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Lab06 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lab06));
        
        string IMigrationMetadata.Id
        {
            get { return "201909112017131_Lab06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
